### ISSUE TITLE
Sqlite3 3.25.0 dependency

### ISSUE THREAD

**Issue by anamileva** [blue-marble/gridpath#161]
The curtailment plot does not seem to work on my machine.

This is the traceback:
```
Traceback (most recent call last):
  File "curtailment_heatmap_plot.py", line 344, in <module>
    main()
  File "curtailment_heatmap_plot.py", line 323, in main
    curtailment_type=parsed_args.curtailment_type
  File "curtailment_heatmap_plot.py", line 175, in create_data_df
    curtailment_type)
  File "curtailment_heatmap_plot.py", line 156, in get_curtailment
    curtailment = c.execute(sql, (scenario_id, load_zone, period, stage))
sqlite3.OperationalError: near "(": syntax error
```

The error seems to occur at the `PARTITION BY` clause. My sqlite3 version is 3.24.0 and it appears ["Window function support was first added to SQLite with release version 3.25.0 (2018-09-15)"](https://sqlite.org/windowfunctions.html#history). I'm using the Python 3.7.4 distribution installed with pyenv. Upgrading Python's built-in sqlite3 seems non-trivial.

@gerritdm, could you provide some more info on your system setup?

**Comment by milindsmart** [comment]
I believe this can be closed now because Python 3.9, the lowest version tested with GridPath, comes with Sqlite 3.42.0.
