### ISSUE TITLE
Intermittent FOREIGN KEY constraint failed while importing project subscenarios

### ISSUE THREAD

**Issue by milindsmart** [blue-marble/gridpath#729]
I intermittently face issues such as 

```
(gp03) C:\Users\milind\Work\Projects-External\GridPath\software\repo-gp03>python db\utilities\port_csvs_to_db.py --database ..\KA_v0.6_Sep2020a.db --csv_location ..\..\CSVs\csvs_kn_03092020
Importing data for subscenario solver_options_id, table options_solver from ..\..\CSVs\csvs_kn_03092020\solver...
...importing CSV 1_cplex.csv
   ...importing data from 1_cplex.csv
...importing CSV 2_cbc.csv
   ...importing data from 2_cbc.csv
...
...
...
Importing data for subscenario project_specified_fixed_cost_scenario_id, table project_specified_fixed_cost from ..\..\CSVs\csvs_kn_03092020\project/fixed_cost...
...importing CSV 1_1zone_KN.csv
   ...importing data from 1_1zone_KN.csv
...importing CSV 2_2zone_KN_ISGS.csv
   ...importing data from 2_2zone_KN_ISGS.csv
Importing data for subscenario hydro_operational_chars_scenario_id, table project_hydro_operational_chars from ..\..\CSVs\csvs_kn_03092020\project/projwise_hydro_opchar...
...importing CSV AlamattiHydro_KN-1-daily_horizon.csv
   ...importing data from AlamattiHydro_KN-1-daily_horizon.csv
Traceback (most recent call last):
  File "db\utilities\port_csvs_to_db.py", line 398, in <module>
    main()
  File "db\utilities\port_csvs_to_db.py", line 352, in main
    quiet=parsed_args.quiet
  File "db\utilities\port_csvs_to_db.py", line 160, in load_all_from_master_csv
    cols_to_exclude_str, custom_method, inputs_dir, filename, quiet
  File "c:\users\milind\work\projects-external\gridpath\software\repo-gp03\db\utilities\common_functions.py", line 941, in load_all_subscenario_ids_from_dir_to_subscenario_table
    custom_method=custom_method
  File "c:\users\milind\work\projects-external\gridpath\software\repo-gp03\db\utilities\common_functions.py", line 322, in read_all_csv_subscenarios_from_dir_and_insert_into_db
    custom_method=custom_method
  File "c:\users\milind\work\projects-external\gridpath\software\repo-gp03\db\utilities\common_functions.py", line 268, in get_subscenario_data_and_insert_into_db
    skip_subscenario_data=skip_subscenario_data
  File "c:\users\milind\work\projects-external\gridpath\software\repo-gp03\db\utilities\common_functions.py", line 479, in generic_insert_subscenario
    conn, subscenario, table, inputs_data, project_flag, csv_headers
  File "c:\users\milind\work\projects-external\gridpath\software\repo-gp03\db\utilities\common_functions.py", line 907, in generic_insert_subscenario_data
    data=inputs_data)
  File "c:\users\milind\work\projects-external\gridpath\software\repo-gp03\db\common_functions.py", line 76, in spin_on_database_lock
    cursor.executemany(sql, data)
sqlite3.IntegrityError: FOREIGN KEY constraint failed

```

I finally found the cause of this, see : https://github.com/anamileva/gridpath/blob/d672fb0faac8c6e1193ddb8de158b3ed27bb9fe5/db/utilities/common_functions.py#L193-L197 

`project` and `subscenario_id` are keyword arguments. These arguments are columns that will be added to the contents of the CSVs before being INSERTed into `inputs_project_hydro_operational_chars` and other such project-level subscenario tables. The columns are added in the order passed: https://github.com/anamileva/gridpath/blob/d672fb0faac8c6e1193ddb8de158b3ed27bb9fe5/db/utilities/common_functions.py#L112-L114 

Python began [preserving the order of keyword arguments only in v3.6](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep468), and I am still using a Python 3.5 environment. 

I think we have no further reason to stick to Python 3.5, so I advocate making Python 3.6 the minimum version required for GridPath.

**Comment by anamileva** [comment]
Closed with v0.7.0.
