### ISSUE TITLE
Getting error while running the test module 

### ISSUE THREAD

**Issue by alamincse32** [blue-marble/gridpath#957]
Hi, 

Why I am getting this error while I am running this command to test my installation:
**python -m unittest discover tests**

Error:
ERROR: Constructing component 'prev_tmp' from data=None failed:
        TypeError: unhashable type: 'dict'

ERROR: test_data_loaded_correctly (objective.project.test_aggregate_prm_group_costs.TestCapacityThresholdCostsAgg)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "G:\GRIDPATH\gridpath\tests\objective\project\test_aggregate_prm_group_costs.py", line 98, in test_data_loaded_correctly
    instance = m.create_instance(data)
  File "G:\GRIDPATH\sample_venv\lib\site-packages\pyomo\core\base\PyomoModel.py", line 697, in create_instance
    instance.load( data,
  File "G:\GRIDPATH\sample_venv\lib\site-packages\pyomo\core\base\PyomoModel.py", line 734, in load
    self._load_model_data(dp,
  File "G:\GRIDPATH\sample_venv\lib\site-packages\pyomo\core\base\PyomoModel.py", line 787, in _load_model_data
    self._initialize_component(modeldata, namespaces, component_name, profile_memory)
  File "G:\GRIDPATH\sample_venv\lib\site-packages\pyomo\core\base\PyomoModel.py", line 825, in _initialize_component
    declaration.construct(data)
  File "G:\GRIDPATH\sample_venv\lib\site-packages\pyomo\core\base\param.py", line 768, in construct
    self._construct_from_rule_using_setitem()
  File "G:\GRIDPATH\sample_venv\lib\site-packages\pyomo\core\base\indexed_component.py", line 732, in _construct_from_rule_using_setitem
    self._setitem_when_not_present(index, rule(block, index))
  File "G:\GRIDPATH\sample_venv\lib\site-packages\pyomo\core\base\param.py", line 695, in _setitem_when_not_present
    self._validate_value(index, value, _check_domain)
  File "G:\GRIDPATH\sample_venv\lib\site-packages\pyomo\core\base\param.py", line 709, in _validate_value
    if validate_domain and not value in self.domain:
  File "G:\GRIDPATH\sample_venv\lib\site-packages\pyomo\core\base\set.py", line 458, in __contains__
    ans = self.get(value, _NotFound)
  File "G:\GRIDPATH\sample_venv\lib\site-packages\pyomo\core\base\set.py", line 3306, in get
    v = s.get(val, default)
  File "G:\GRIDPATH\sample_venv\lib\site-packages\pyomo\core\base\set.py", line 1232, in get
    if value in self._values:
TypeError: unhashable type: 'dict'

**Comment by anamileva** [comment]
Please make sure to create a Python environment for GridPath, install to it, and activate it before running the tests.
